server:
    port : 8080
  
client:
    port : 80

spring:
  application:
    name: demo
  datasource:
    url: jdbc:oracle:thin:@192.168.1.2:1521:orcl
    username: minh
    password: minhpro
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ur email
    password: ur password
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

api:
    prefix: api/v1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

jwt: 
    expiration : 2592000 #30days
    expiration-refresh-token: 5184000 #60days
    secretKey : /VAQau69iENaScwR1N3QWyJxUBxW+iJ1NnAnj9jMBBI=

logging:
  level:
    # org.hibernate.orm.jdbc.bind: trace
    # org.hibernate.SQL: debug
    # org.hibernate.type: TRACE
    # org.hibernate.type.descriptor.sql: trace
    # org.springframework.security: debug
    # org.springframework.web: debug
    com.shopapp.components.ApiLoggingFilter: DEBUG
  