server:
    port : 8080
  
client:
    port : 5173

spring:
  application:
    name: demo
  datasource:
    url: jdbc:oracle:thin:@192.168.1.2:1521:orcl
    username: minh
    password: minhpro
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: minhnhat.kd.hungyen@gmail.com 
    password: ayja lzxm grhl bzoh
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: <Your clientId>
            clientSecret: <Your clientSecret>
            scope:
              - user:email
              - read:user
          google:
            clientId: <Your clientId>
            clientSecret: <Your clientSecret>
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          facebook:
            clientId: <Your clientId>
            clientSecret: <Your clientSecret>
            scope:
              - email
              - public_profile
  main:
    allow-bean-definition-overriding: true

api:
    prefix: api/v1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

jwt: 
    expiration : 2592000 #30days
    expiration-refresh-token: 5184000 #60days
    secretKey : /VAQau69iENaScwR1N3QWyJxUBxW+iJ1NnAnj9jMBBI=

#AWS credentials
aws:
  accessKey: < Your accessKey >
  secretKey: < Your secretKey >
  region: ap-southeast-1
  s3:
    bucket: tobioxd

logging:
  level:
    # org.hibernate.orm.jdbc.bind: trace
    # org.hibernate.SQL: debug
    # org.hibernate.type: TRACE
    # org.hibernate.type.descriptor.sql: trace
    # org.springframework.security: debug
    # org.springframework.web: debug
    com.shopapp.components.ApiLoggingFilter: DEBUG